version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Ubuntu2004

init:
  - git config --global core.autocrlf false
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

nuget:
  disable_publish_on_pr: true

stack: node 14

environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYfgI1QRePD4ATwTgDSbO0Zj5SBtGEXzzCeDlthZ2+ZkUDqaDynmCd7xxD8VLJd/PL5U11cabVuYS17RvK4AuH56yLQC/R9KcvCioyA+j2HlbjftCPcEqNrPT7ZciNPS0O61q2Ya5pXEtKcdUgr3fIkRHyucGHTIO9tt7uK4cf/MosNh0ak9pyqoxO54NlPcmMnsJqJ0TZER7/gzAsq5uyjZ4n9qPOBw6jM2E1a7jne98WwcI05miHm8GYdoLvyWCo1OJ0KVQu7jV9FAl5dYBPV88eGc+2/z65+ZBltwPMkVHuNcFC1Bm7EJjli5ULpzy6D83pksFoq2aVRxVTTC8TrcqlSrrpE9p45b5XOEE+AfOO66MwB95TVGO2CVQjxObLxwcVhDHW6zUZ4e7b1nWSw1SCmfPq1ifNnu1i2QTuYlXDuP6E4TFnUATL1yQn8ZIISakDPIBi9XStkqc0EgWUbxs0Wx8ucqSdRXo/LmIbDXctNo7k//ce9sWin2fG/7k= pavel@DESKTOP-B0BA809
  NPM_TOKEN:
    secure: Gx5yyFrlELZY4DNW/uAuiXdhUADacNqi3LptQwldv8O61KpYyiDUniA8lBJ5jfne

install:
  - docker pull selenoid/vnc:chrome_84.0
  - docker-compose up -d

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $version = $tagName.Substring(1)
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $version = $version.Substring(0, $version.IndexOf("-release"))
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
        $matchVersion = Select-String -Path ./version.json -Pattern "`"version`": `"$version`""
        if ($matchVersion -eq $null)
        {
          Write-Error "Version in tag ($version) does not match version in version.json"
        }
      }
  - dotnet --info
  - dotnet restore ./DbViewer.sln --verbosity minimal
  - dotnet tool restore
  - yarn --cwd db-viewer-ui install --frozen-lockfile

build_script:
  - dotnet build --configuration Release ./DbViewer.sln
  - dotnet pack --no-build --configuration Release ./DbViewer.sln
  - yarn --cwd db-viewer-ui build

before_test:
  - dotnet ef database update --project ./DbViewer.TestApi/DbViewer.TestApi.csproj --no-build --configuration Release
  - ps: Start-Process dotnet -ArgumentList "./DbViewer.TestApi/bin/net6.0/SkbKontur.DbViewer.TestApi.dll"
  - ps: |
        Set-Location -Path db-viewer-ui
        Start-Process yarn start:prod
        Set-Location -Path ..

test_script:
  - dotnet jb cleanupcode DbViewer.sln --profile=CatalogueCleanup --exclude=./DbViewer.TestApi/Migrations/*.cs --verbosity=WARN
  - git diff --exit-code
  - dotnet test --no-build --configuration Release ./DbViewer.Tests/DbViewer.Tests.csproj
  - yarn --cwd db-viewer-ui lint

after_test:
  - ps: |
      if ($env:SHOULD_PUBLISH_NUGET_PACKAGE -eq "true")
      {
        npm config set '//registry.npmjs.org/:_authToken' $env:NPM_TOKEN
        $fileNames = Get-ChildItem -Path "db-viewer-ui/dist" -Recurse -Include *.tgz
        foreach ($file in $fileNames)
        {
          Write-Host "Will publish npm package $($file.Name)" -ForegroundColor "Green"
          npm publish $file.FullName --quiet
        }
      }

artifacts:
  - path: './DbViewer*/bin/Release/*.nupkg'
  - path: './db-viewer-ui/dist/*.tgz'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: J0fb96dtj1vkQ9psZQVgWvua4YCdABBGvH+sqR6dTiJt8d8cUIG7V7e03+5PHkE3
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
