version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2019

init:
  - cmd: git config --global core.autocrlf false

nuget:
  disable_publish_on_pr: true

environment:
  NPM_TOKEN:
    secure: Gx5yyFrlELZY4DNW/uAuiXdhUADacNqi3LptQwldv8O61KpYyiDUniA8lBJ5jfne

install:
  - cmd: docker-switch-linux
  - cmd: docker pull selenoid/vnc:chrome_84.0
  - cmd: docker-compose up -d

before_build:
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $version = $tagName.Substring(1)
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $version = $version.Substring(0, $version.IndexOf("-release"))
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
        $matchVersion = Select-String -Path ./version.json -Pattern "`"version`": `"$version`""
        if ($matchVersion -eq $null)
        {
          Write-Error "Version in tag ($version) does not match version in version.json"
        }
      }
  - cmd: dotnet --info
  - cmd: dotnet restore ./DbViewer.sln --verbosity minimal
  - cmd: dotnet tool restore
  - cmd: yarn install --frozen-lockfile

build_script:
  - cmd: dotnet build --configuration Release ./DbViewer.sln
  - cmd: dotnet pack --no-build --configuration Release ./DbViewer.sln
  - cmd: yarn build

before_test:
  - cmd: dotnet ef database update --project ./DbViewer.TestApi/DbViewer.TestApi.csproj --no-build --configuration Release
  - ps: Start-Process ./DbViewer.TestApi/bin/net5.0/SkbKontur.DbViewer.TestApi.exe
  - ps: Start-Process yarn start:prod

test_script:
  - cmd: dotnet jb cleanupcode DbViewer.sln --profile=CatalogueCleanup --exclude=./DbViewer.TestApi/Migrations/*.cs --verbosity=WARN
  - cmd: git diff --exit-code
  - cmd: dotnet test --no-build --configuration Release ./DbViewer.Tests/DbViewer.Tests.csproj
  - cmd: yarn lint

after_test:
  - ps: |
      if ($env:SHOULD_PUBLISH_NUGET_PACKAGE -eq "true")
      {
        npm config set '//registry.npmjs.org/:_authToken' $env:NPM_TOKEN
        $fileNames = Get-ChildItem -Path "db-viewer-ui/dist" -Recurse -Include *.tgz
        foreach ($file in $fileNames)
        {
          Write-Host "Will publish npm package $($file.Name)" -ForegroundColor "Green"
          npm publish $file.FullName --quiet
        }
      }

artifacts:
  - path: './DbViewer*/bin/Release/*.nupkg'
  - path: './db-viewer-ui/dist/*.tgz'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: y2RPf+gBBqffQVm8pg9qZcg99m7K8hsSa4z7VHvIE6t+kuO7r/oIqTVcryZzL93D
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
