// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkbKontur.DbViewer.TestApi.EntityFramework;

namespace SkbKontur.DbViewer.TestApi.Migrations
{
    [DbContext(typeof(EntityFrameworkDbContext))]
    partial class EntityFrameworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SkbKontur.DbViewer.TestApi.EntityFramework.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CompositeKey")
                        .HasColumnType("text");

                    b.Property<bool>("Boolean")
                        .HasColumnType("boolean");

                    b.Property<Customer>("Customer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("CustomerSerialized")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Integer")
                        .HasColumnType("integer");

                    b.Property<string>("String")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "CompositeKey");

                    b.HasIndex("Boolean", "Integer", "String", "DateTime", "DateTimeOffset");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("SkbKontur.DbViewer.TestApi.EntityFramework.UsersTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
